from .abstract import AbstractJointMap


class G8fMap(AbstractJointMap):

    @property
    def joint_map(self):
        return {'Root_M': 'hip',
                'Pelvis_M': 'pelvis',
                'ButtockBase_R': '',
                'ButtockEnd_R': '',
                'Spine1_M': 'abdomenLower',
                'Spine2_M': 'abdomenUpper',
                'Spine3_M': 'chestLower',
                'Chest_M': 'chestUpper',
                'Neck_M': 'neckLower',
                'Head_M': 'head',
                'HeadEnd_M': '',
                'Jaw_M': 'lowerJaw',
                'JawEnd_M': 'Chin',
                'Tongue1_M': 'tongue01',
                'Tongue2_M': 'tongue02',
                'Tongue3_M': 'tongue03',
                'Tongue4_M': 'tongue04',
                'TongueEnd_M': '',
                'Hip_R': 'rThighBend',
                'Knee_R': 'rShin',
                'Ankle_R': 'rFoot',
                'Heel_R': '',
                'Toes_R': 'rToe',
                'FootSideInner_R': '',
                'FootSideOuter_R': '',
                'ToesEnd_R': '',
                'BreastBase_R': 'rPectoral',
                'BreastMid_R': '',
                'BreastEnd_R': '',
                'Scapula_R': 'rCollar',
                'Shoulder_R': 'rShldrBend',
                'Elbow_R': 'rForearmBend',
                'Wrist_R': 'rHand',
                'ThumbFinger1_R': 'rThumb1',
                'ThumbFinger2_R': 'rThumb2',
                'ThumbFinger3_R': 'rThumb3',
                'ThumbFinger4_R': '',
                'IndexFinger1_R': 'rIndex1',
                'IndexFinger2_R': 'rIndex2',
                'IndexFinger3_R': 'rIndex3',
                'IndexFinger4_R': '',
                'MiddleFinger1_R': 'rMid1',
                'MiddleFinger2_R': 'rMid2',
                'MiddleFinger3_R': 'rMid3',
                'MiddleFinger4_R': '',
                'RingFinger1_R': 'rRing1',
                'RingFinger2_R': 'rRing2',
                'RingFinger3_R': 'rRing3',
                'RingFinger4_R': '',
                'PinkyFinger1_R': 'rPinky1',
                'PinkyFinger2_R': 'rPinky2',
                'PinkyFinger3_R': 'rPinky3',
                'PinkyFinger4_R': '',
                'Eye_R': 'rEye',
                'EyeEnd_R': ''
                }

    @property
    def custom_xforms(self):
        return {'BreastEnd_R': (-0.7507, 0.0609, 2.0745),
                'BreastMid_R': (-5.4764, 4.5825, 15.071),
                'ButtockBase_R': (-6.7316, -11.1316, -7.9212),
                'ButtockEnd_R': (0.0, 0.0202, -4.462),
                'EyeEnd_R': (-0.0, 0.0, 1.9899),
                'FootSideInner_R': (4.1749, -1.5189, 2.0264),
                'FootSideOuter_R': (-4.1465, -1.5189, -1.6646),
                'HeadEnd_M': (-0.0002, 19.7225, -0.0),
                'Heel_R': (1.591, -6.8412, -6.9217),
                'IndexFinger4_R': (-1.1097, -1.6503, 0.097),
                'MiddleFinger4_R': (-1.2055, -1.7125, -0.0127),
                'PinkyFinger4_R': (-1.0251, -1.3298, -0.1708),
                'RingFinger4_R': (-1.1531, -1.7006, -0.0962),
                'ThumbFinger4_R': (-0.7817, -2.2185, 1.468),
                'ToesEnd_R': (-1.7017, -1.5189, 4.9737),
                'TongueEnd_M': (0.0, 0.0426, 1.4055)}
